baseURL = "https://tracker.neverfapdeluxe.com/"
title = "NeverFap Deluxe Tracker | Get Immediate Help With Your Porn Addiction."
languageCode = "en-us"
theme = "tracker_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-4"
